// src/app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Computer Science App",
  description: "Generated by Next.js",
};

type RootLayoutProps = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* Header */}
        <header className="text-center py-6 bg-gray-50 shadow-md">
          <h1 className="text-4xl font-bold text-gray-800">Computer Science</h1>
        </header>

        {/* Navbar */}
        <nav className="flex justify-center space-x-6 px-6 py-4 bg-white shadow sticky top-0 z-50">
          <Link
            href="/"
            className="text-gray-700 hover:text-blue-600 transition duration-200"
          >
            Home
          </Link>
          <Link
            href="/about"
            className="text-gray-700 hover:text-blue-600 transition duration-200"
          >
            About
          </Link>
          <Link
            href="/DynNav_member"
            className="text-gray-700 hover:text-blue-600 transition duration-200"
          >
            Member
          </Link>
          <Link
            href="/portfolio"
            className="text-gray-700 hover:text-blue-600 transition duration-200"
          >
            Portfolio
          </Link>
          <Link
            href="/teacher"
            className="text-gray-700 hover:text-blue-600 transition duration-200"
          >
            Teacher
          </Link>
          <Link
            href="/Contact"
            className="text-gray-700 hover:text-blue-600 transition duration-200"
          >
            Contact
          </Link>
        </nav>

        {/* Main content */}
        <main className="p-6">{children}</main>
      </body>
    </html>
  );
}
